language: node_js
node_js:
 - "node"
cache: yarn

jobs:
  include:
    - stage: intall
      script:
        - npm install
    - stage: test
      script:
        - yarn
        - yarn test
    - stage: deploy
      script:
        - echo 'Success!!'