language: node_js
node_js:
 - "node"
cache: yarn

jobs:
  include:
    - stage: intall
      script:
        - npm install
    - stage: test
      script:
        - yarn
        - yarn test
    - stage: deploy
      script:
        - echo 'Success!!'
stages:
  - name: install
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master